spring:
  application:
    name: wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true

server:
  port: 8080